const DATA = [
    {
        username: 'İsmail Onur',
        message: "I'm a software developer",
        time: '5 Min',
        numberMessage: '2',
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Enes Can Güneş',
        message: "I like software",
        time: '2 Min',
        numberMessage: false,
        tick: true,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Elmander Viking',
        message: "Lorem ipsum dolor sit amet",
        time: '15.12.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Susan Santos',
        message: "Hi, I'm Susan",
        time: '21.11.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Lucas Stone',
        message: "Lorem ipsum dolor sit amet",
        time: '15.07.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Alex Viking',
        message: "Lorem ipsum dolor sit amet",
        time: '15.12.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Mary Santos',
        message: "Hi, I'm Susan",
        time: '21.11.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Gigi Stone',
        message: "Lorem ipsum dolor sit amet",
        time: '15.07.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Elmander Viking',
        message: "Lorem ipsum dolor sit amet",
        time: '15.12.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Susan Santos',
        message: "Hi, I'm Susan",
        time: '21.11.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Lucas Stone',
        message: "Lorem ipsum dolor sit amet",
        time: '15.07.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Elmander Viking',
        message: "Lorem ipsum dolor sit amet",
        time: '15.12.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Susan Santos',
        message: "Hi, I'm Susan",
        time: '21.11.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
    {
        username: 'Lucas Stone',
        message: "Lorem ipsum dolor sit amet",
        time: '15.07.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/',
    },
];

export default DATA;