const DATA = [
    {
        username: 'İsmail Onur',
        message: "I'm a software developer",
        time: '5 Min',
        numberMessage: '2',
        tick: false,
        photo: 'https://picsum.photos/200',
    },
    {
        username: 'Enes Can Güneş',
        message: "I like software",
        time: '2 Min',
        numberMessage: false,
        tick: true,
        photo: 'https://picsum.photos/201',
    },
    {
        username: 'Elmander Viking',
        message: "Lorem ipsum dolor sit amet",
        time: '15.12.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/202',
    },
    {
        username: 'Susan Santos',
        message: "Hi, I'm Susan",
        time: '21.11.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/203',
    },
    {
        username: 'Lucas Stone',
        message: "Lorem ipsum dolor sit amet",
        time: '15.07.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/204',
    },
    {
        username: 'Alex Viking',
        message: "Lorem ipsum dolor sit amet",
        time: '15.12.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/205',
    },
    {
        username: 'Mary Santos',
        message: "Hi, I'm Susan",
        time: '21.11.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/206',
    },
    {
        username: 'Gigi Stone',
        message: "Lorem ipsum dolor sit amet",
        time: '15.07.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/207',
    },
    {
        username: 'Elmander Viking',
        message: "Lorem ipsum dolor sit amet",
        time: '15.12.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/208',
    },
    {
        username: 'Susan Santos',
        message: "Hi, I'm Susan",
        time: '21.11.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/209',
    },
    {
        username: 'Lucas Stone',
        message: "Lorem ipsum dolor sit amet",
        time: '15.07.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/210',
    },
    {
        username: 'Elmander Viking',
        message: "Lorem ipsum dolor sit amet",
        time: '15.12.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/211',
    },
    {
        username: 'Susan Santos',
        message: "Hi, I'm Susan",
        time: '21.11.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/222',
    },
    {
        username: 'Lucas Stone',
        message: "Lorem ipsum dolor sit amet",
        time: '15.07.2020',
        numberMessage: false,
        tick: false,
        photo: 'https://picsum.photos/213',
    },
];

export default DATA;